# Generated by Django 4.2.5 on 2023-10-21 04:59

import Ecom_Web.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0004_remove_connector_active_product_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('first_phone_number', models.CharField(max_length=15)),
                ('second_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('primary_address', models.BooleanField(blank=True, default=False, null=True)),
                ('delete_address', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='required*', max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(help_text='required*', max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('delete_cart', models.BooleanField(default=False)),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect', to='adminpanel.connector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateTimeField(default=Ecom_Web.models.get_delivery_date)),
                ('total_price', models.CharField(max_length=10)),
                ('total_item', models.CharField(max_length=10)),
                ('payment_method', models.CharField(choices=[('online', 'Online Payment'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancel', 'Canceled'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user_address', to='Ecom_Web.address')),
                ('products', models.ManyToManyField(related_name='order_product', to='adminpanel.connector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('NM', 'Color not match'), ('WS', 'Wrong size'), ('QG', 'Quality not good')], max_length=2)),
                ('text', models.TextField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom_Web.order')),
            ],
        ),
    ]
