# Generated by Django 4.2.5 on 2023-10-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_Web', '0005_userwishlist_userwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20)),
                ('expire_date', models.DateField()),
                ('amount_to_reduce', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_purchase', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
