# Generated by Django 4.2.5 on 2023-10-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_Web', '0005_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
