# Generated by Django 4.2.5 on 2023-10-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_Web', '0006_coupon'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('amount_to_reduce__lte', models.F('minimum_purchase'))), name='check_amount_to_reduce'),
        ),
    ]
