# Generated by Django 4.2.5 on 2023-10-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_Web', '0008_coupon_maximum_apply_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount_to_reduce',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='maximum_apply',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
