# Generated by Django 4.2.5 on 2023-10-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_Web', '0009_alter_coupon_amount_to_reduce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_product',
            field=models.BooleanField(default=False),
        ),
    ]
