# Generated by Django 4.2.5 on 2023-11-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_Web', '0010_order_return_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('cash_on_delivery', 'Cash on Delivery'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
