# Generated by Django 4.2.5 on 2023-11-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_Web', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productordered',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
