# Generated by Django 4.2.5 on 2023-10-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('normal_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='required*', max_length=255, unique=True)),
                ('description', models.TextField(help_text='required*')),
                ('price', models.DecimalField(decimal_places=2, help_text='required*', max_digits=10)),
                ('brand', models.ForeignKey(help_text='required*', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.brand')),
                ('category', models.ForeignKey(default=1, help_text='required*', on_delete=django.db.models.deletion.SET_DEFAULT, to='adminpanel.category')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('first_preference', models.BooleanField(default=False)),
                ('sale', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_color', to='adminpanel.color')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_image', to='adminpanel.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_product', to='adminpanel.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_size', to='adminpanel.size')),
            ],
        ),
    ]
