# Generated by Django 4.2.5 on 2023-10-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_connector_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='first_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connector',
            name='sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='connector',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_color', to='adminpanel.color'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_image', to='adminpanel.productimage'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_product', to='adminpanel.product'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_size', to='adminpanel.size'),
        ),
    ]
