# Generated by Django 4.2.5 on 2023-10-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_category_name_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
