# Generated by Django 4.2.5 on 2023-10-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_color_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
    ]
