# Generated by Django 4.2.5 on 2023-10-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_brand_active_category_active_category_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(default='unnamed', max_length=255, null=True, unique=True),
        ),
    ]
