# Generated by Django 4.2.5 on 2023-10-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_color_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
