# Generated by Django 4.2.5 on 2023-10-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_color_active_size_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('name', 'color'), name='unique_active_color'),
        ),
    ]
