# Generated by Django 4.2.5 on 2023-10-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_alter_color_color_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('size',), name='unique_active_size'),
        ),
    ]
