# Generated by Django 4.2.5 on 2023-10-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_alter_size_size_size_unique_active_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='color',
            name='unique_active_color',
        ),
        migrations.RemoveConstraint(
            model_name='size',
            name='unique_active_size',
        ),
    ]
