# Generated by Django 4.2.5 on 2023-10-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_remove_color_unique_active_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
