# Generated by Django 4.2.5 on 2023-10-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_alter_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(help_text='required*', max_length=255),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(help_text='required*', max_length=255),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(help_text='required*'),
        ),
    ]
