# Generated by Django 4.2.5 on 2023-10-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
