# Generated by Django 4.2.5 on 2023-10-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='acti',
            field=models.BooleanField(default=True),
        ),
    ]
