# Generated by Django 4.2.5 on 2023-10-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
