# Generated by Django 4.2.5 on 2023-10-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='act',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, help_text='optional', null=True),
        ),
    ]
