# Generated by Django 4.2.5 on 2023-10-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_connector_act_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='act',
        ),
    ]
