# Generated by Django 4.2.5 on 2023-10-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_remove_connector_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
