# Generated by Django 4.2.5 on 2023-10-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_ratting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratting',
            name='comment',
        ),
    ]
